parameters:
  - name: Environment_ShortName
    type: string

jobs:
  - deployment: build_${{ parameters.Environment_ShortName }}
    displayName: 'Deploy ${{ parameters.Environment_ShortName }}'
    environment: 'Test Environment'

    strategy:
      runOnce:
          deploy:
            steps:

              - download : none
          
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  targetPath: '$(System.DefaultWorkingDirectory)'

              - task: PowerShell@2
                name: identify_deploy_version
                inputs:
                  targetType: 'inline'
                  script: |
                      ls
                      write-host "Path is $(Pipeline.Workspace)"
                      write-host "System path $(System.DefaultWorkingDirectory)"
                      Write-host "${{ parameters.Environment_ShortName }}"
                      $csOutgoingVersion='blue'
                      Write-Host "##vso[task.setvariable variable=cs_OutgoingVersion;isOutput=true]$csOutgoingVersion"

              - task: CmdLine@2
                displayName: 'Swap Production CloudService ${{ variables.identify_deploy_version.cs_OutgoingVersion }} with Staging'
                inputs:
                  script: |
                      echo  '$(System.DefaultWorkingDirectory)'
                      dir $(System.DefaultWorkingDirectory)
